sequenceDiagram
  participant participant_isInfraShape as isInfraShape
  participant participant_isInfraWorkloadSpec as isInfraWorkloadSpec
  participant participant_isRecord as isRecord
  participant_isInfraWorkloadSpec->>participant_isInfraShape: isInfraShape()
  participant_isInfraShape->>participant_isRecord: isRecord()
  participant_isRecord-->>participant_isInfraShape: return
  participant_isInfraShape-->>participant_isInfraWorkloadSpec: return
