sequenceDiagram
  participant participant_isRecord as isRecord
  participant participant_isSerializableSet as isSerializableSet
  participant_isSerializableSet->>participant_isRecord: isRecord()
  participant_isRecord-->>participant_isSerializableSet: return
