/* This file is generated by @ankhorage/devtools. Do not edit manually. */
import type { StructureDescriptorDocument } from '@ankhorage/contracts/structure';

export const STRUCTURE_DESCRIPTOR_COMPILER_VERSION = '5.9.3';
export const STRUCTURE_DESCRIPTOR_FINGERPRINT = 'sha256:f66f96ecff70a6e338da52775a03466dc4fdfddbda881019b127d6463dcb1a29';

export const STRUCTURE_DESCRIPTOR = {
  "protocolVersion": 1,
  "packageName": "@ankhorage/contracts",
  "packageVersion": "22.1.1",
  "roots": {
    "screen-metadata": "ScreenMetadataSpec"
  },
  "descriptors": {
    "ScreenMetadataSpec": {
      "id": "ScreenMetadataSpec",
      "descriptor": {
        "kind": "object",
        "fields": {
          "description": {
            "value": {
              "kind": "scalar",
              "type": "string"
            },
            "optional": true
          },
          "id": {
            "value": {
              "kind": "scalar",
              "type": "string"
            }
          },
          "name": {
            "value": {
              "kind": "scalar",
              "type": "string"
            }
          },
          "title": {
            "value": {
              "kind": "scalar",
              "type": "string"
            },
            "optional": true
          }
        }
      }
    }
  }
} as const satisfies StructureDescriptorDocument;
