/* This file is generated by @ankhorage/devtools. Do not edit manually. */
import type { StructureDescriptorDocument } from '@ankhorage/contracts/structure';

export const STRUCTURE_DESCRIPTOR_COMPILER_VERSION = '6.0.3';
export const STRUCTURE_DESCRIPTOR_FINGERPRINT = 'sha256:8a7ff196412aee460cfda7c9cca08ffb6d055ceca7432b611330b39c7ec81ab3';

export const STRUCTURE_DESCRIPTOR = {
  "protocolVersion": 1,
  "packageName": "@ankhorage/contracts",
  "packageVersion": "22.2.0",
  "roots": {
    "screen-metadata": "ScreenMetadataSpec",
    "screen-requirements": "ScreenRequirements"
  },
  "descriptors": {
    "AnkhorageCapabilityName": {
      "id": "AnkhorageCapabilityName",
      "descriptor": {
        "kind": "enum",
        "values": [
          "barcodeScanner",
          "cameraPreview",
          "clipboard",
          "ebookReader",
          "filePicker",
          "location",
          "mediaPicker",
          "notifications"
        ]
      }
    },
    "AnkhoragePermissionName": {
      "id": "AnkhoragePermissionName",
      "descriptor": {
        "kind": "enum",
        "values": [
          "camera",
          "clipboard",
          "locationBackground",
          "locationForeground",
          "mediaLibrary",
          "mediaLibraryWrite",
          "microphone",
          "notifications"
        ]
      }
    },
    "ScreenMetadataSpec": {
      "id": "ScreenMetadataSpec",
      "descriptor": {
        "kind": "object",
        "fields": {
          "description": {
            "value": {
              "kind": "scalar",
              "type": "string"
            },
            "optional": true
          },
          "id": {
            "value": {
              "kind": "scalar",
              "type": "string"
            }
          },
          "name": {
            "value": {
              "kind": "scalar",
              "type": "string"
            }
          },
          "title": {
            "value": {
              "kind": "scalar",
              "type": "string"
            },
            "optional": true
          }
        }
      }
    },
    "ScreenRequirements": {
      "id": "ScreenRequirements",
      "descriptor": {
        "kind": "object",
        "fields": {
          "capabilities": {
            "value": {
              "kind": "set",
              "member": {
                "kind": "ref",
                "id": "AnkhorageCapabilityName"
              }
            },
            "optional": true
          },
          "permissions": {
            "value": {
              "kind": "set",
              "member": {
                "kind": "ref",
                "id": "AnkhoragePermissionName"
              }
            },
            "optional": true
          }
        }
      }
    }
  }
} as const satisfies StructureDescriptorDocument;
