import type { DbCollectionDefinition } from '../db';
import type { DatabaseAdapterRef } from './refs';
import type { DataContractValue } from './values';

export const GENERATED_API_CRUD_OPERATIONS = [
  'list',
  'read',
  'create',
  'update',
  'delete',
] as const;
export type GeneratedApiCrudOperation = (typeof GENERATED_API_CRUD_OPERATIONS)[number];

export type GeneratedApiId = string;
export type GeneratedApiResourceId = string;
export type GeneratedApiSeedRecord = Readonly<Record<string, DataContractValue>>;

export interface GeneratedApiAuthRequirement {
  readonly required?: boolean;
  readonly roles?: readonly string[];
  readonly permissions?: readonly string[];
  readonly policy?: string;
  readonly metadata?: DataContractValue;
}

export interface GeneratedApiOperationPolicyRef {
  readonly id: string;
  readonly operation?: GeneratedApiCrudOperation;
}

export interface GeneratedApiResourceDefinition {
  readonly id: GeneratedApiResourceId;
  readonly name?: string;
  readonly description?: string;
  readonly path: string;
  readonly collection: DbCollectionDefinition;
  readonly operations: readonly GeneratedApiCrudOperation[];
  readonly seed?: readonly GeneratedApiSeedRecord[];
  readonly policies?: readonly GeneratedApiOperationPolicyRef[];
  readonly metadata?: DataContractValue;
}

/**
 * Canonical desired state for an API authored and generated by Ankhorage.
 *
 * The initial supported generated implementation is REST/CRUD backed by an
 * existing database adapter. Runtime and binding consumers use the normalized
 * generated API data-source projection instead of reading this definition.
 */
export interface GeneratedApiDefinition {
  readonly id: GeneratedApiId;
  readonly protocol: 'rest';
  readonly name?: string;
  readonly description?: string;
  readonly basePath: string;
  readonly database: DatabaseAdapterRef;
  readonly resources: readonly GeneratedApiResourceDefinition[];
  readonly auth?: GeneratedApiAuthRequirement;
  readonly metadata?: DataContractValue;
}

export type GeneratedApiRegistry = Readonly<Record<GeneratedApiId, GeneratedApiDefinition>>;
